# Generated by Django 4.0.3 on 2022-03-31 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_realtor',
            field=models.BooleanField(default=False),
        ),
    ]
