# Generated by Django 4.0.3 on 2022-03-31 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_user_is_realtor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='is_realtor',
            field=models.BooleanField(default=False, help_text='Designates whether this user  is a realtor ', verbose_name='is_realtor'),
        ),
    ]
